repos:
  - repo: local
    hooks:
      - id: generate-docs
        name: Generate Markdown documentation and convert to HTML
        entry: /bin/bash -c './generate_docs.sh'
        language: system
        types: [file]

#repos:
#  - repo: https://github.com/pre-commit/pre-commit-hooks
#    rev: v4.3.0
#    hooks:
#      - id: trailing-whitespace
#      - id: end-of-file-fixer
#      - id: check-yaml
#      - id: check-added-large-files
#
#  - repo: https://github.com/dnephin/pre-commit-golang
#    rev: v0.5.0
#    hooks:
#      - id: go-fmt
#      - id: go-imports
#      - id: no-go-testing
#      - id: golangci-lint
#      - id: go-unit-tests